#!/usr/bin/env python3
"""
audit_targets.py - Target selection & release-freshness ranker (Edge 1 + Edge 3).

Breadth-first auditing is exhausted (most DB plugins already have an audit dir).
The remaining value is: (A) re-auditing the DIFF of plugins that shipped a new
release since you last audited them, and (B) the handful never audited yet.
This script ranks both queues by an expected-value proxy (install count x
freshness) using ONLY data already on disk - no network unless --online.

Data sources (all already present in this repo):
  - databases/*.db   -> Plugins(slug, version, active_installs, last_updated, ...)
  - audit/<slug>/<version>/   -> what you have already audited
  - databases/pattern_accumulator.db -> which slugs already yielded findings

Usage:
  python audit_targets.py                       # offline ranking, top 40, writes targets.md
  python audit_targets.py --top 100
  python audit_targets.py --min-installs 100000
  python audit_targets.py --max-installs 500000     # only <=500k installs (less contested)
  python audit_targets.py --online --top 25     # poll wordpress.org for TRUE current version
  python audit_targets.py --skip-mined          # drop plugins that already gave >=3 findings
  python audit_targets.py --prepare 3           # download top 3 so they are audit-ready
  python audit_targets.py --out my_targets.md   # write the checklist somewhere else

Importable helpers (used by daily_targets.py):
  rank_targets(...)        -> (new_release, never, polled)
  render_targets_md(...)   -> markdown string
  prepare_targets(...)     -> downloads the top N items via the downloader
"""
import argparse
import glob
import json
import os
import re
import subprocess
import sqlite3
import sys
import time
from datetime import datetime

ROOT = os.path.dirname(os.path.abspath(__file__))
AUDIT_DIR = os.path.join(ROOT, "audit")
PLUGINS_DIR = os.path.join(ROOT, "plugins")
DB_GLOB = os.path.join(ROOT, "databases", "*.db")
ACC_DB = os.path.join(ROOT, "databases", "pattern_accumulator.db")
DOWNLOADER = os.path.join(ROOT, "wp-plugin-downlauditor.py")
RULES_DIR = os.path.join(ROOT, "semgrep_rules")  # custom corpus the rest of the DB was scanned with
WP_API = ("https://api.wordpress.org/plugins/info/1.2/"
          "?action=plugin_information&request[slug]={slug}")

# Plugins picked over this many confirmed findings are deprioritised / skippable.
MINED_THRESHOLD = 3


def vkey(v):
    """Comparable version key without the `packaging` dependency."""
    if not v:
        return ()
    parts = re.split(r"[._-]", str(v))
    out = []
    for p in parts:
        m = re.match(r"^(\d+)", p)
        out.append(int(m.group(1)) if m else 0)
    return tuple(out)


def load_db_plugins():
    """Return {slug: {version, installs, last_updated, added}} (best row across tier DBs)."""
    plugins = {}
    for db in glob.glob(DB_GLOB):
        if os.path.basename(db).startswith("pattern_accumulator"):
            continue
        try:
            con = sqlite3.connect(db)
            rows = con.execute(
                "SELECT slug, version, active_installs, last_updated, added_date FROM Plugins"
            ).fetchall()
            con.close()
        except sqlite3.Error:
            continue
        for slug, version, installs, last_updated, added in rows:
            cur = plugins.get(slug)
            installs = installs or 0
            # keep the row with the newest version (and max installs seen)
            if cur is None or vkey(version) > vkey(cur["version"]):
                plugins[slug] = {
                    "version": version, "installs": max(installs, cur["installs"] if cur else 0),
                    "last_updated": last_updated, "added": added,
                }
            elif installs > cur["installs"]:
                cur["installs"] = installs
    return plugins


# A version dir counts as "audited" only if it holds a real audit artifact. A dir
# containing only DIFF.md (pre-generated by diff_audit.py before the audit runs)
# must NOT be treated as audited, or the plugin would wrongly drop out of the diff
# queue and diff_audit would pick the wrong baseline.
_AUDIT_MARKERS = ("findings.md", "audit-context.md", "pipeline-state.md")

# A finding-first DIFF-AUDIT (read DIFF.md -> confirm the bug -> run the vuln-report
# + poc-generator skills) can skip the pipeline scaffolding above and leave ONLY
# DIFF.md + reports/ + poc/. A non-empty reports/ or poc/ dir is an unambiguous
# "an audit happened here" signal, so it counts too — otherwise such a completed
# audit looks un-audited and its version re-surfaces in targets.md (and diff_audit
# picks a stale baseline). DIFF.md alone still must NOT count (those dirs are empty
# of reports/poc), preserving the invariant above.
_AUDIT_ARTIFACT_DIRS = ("reports", "poc")


def _nonempty_dir(path):
    try:
        return any(not n.startswith(".") for n in os.listdir(path))
    except OSError:
        return False


def _is_real_audit(vdir):
    try:
        names = os.listdir(vdir)
    except OSError:
        return False
    if any(m in names for m in _AUDIT_MARKERS):
        return True
    return any(d in names and _nonempty_dir(os.path.join(vdir, d))
               for d in _AUDIT_ARTIFACT_DIRS)


def audited_versions(slug):
    d = os.path.join(AUDIT_DIR, slug)
    if not os.path.isdir(d):
        return []
    return [v for v in os.listdir(d)
            if os.path.isdir(os.path.join(d, v)) and _is_real_audit(os.path.join(d, v))]


def load_mined_slugs():
    """Slugs that already produced >=1 confirmed finding (deprioritize: picked over)."""
    mined = {}
    if not os.path.exists(ACC_DB):
        return mined
    try:
        con = sqlite3.connect(ACC_DB)
        for slug, n in con.execute(
            "SELECT plugin_slug, COUNT(*) FROM findings WHERE status='TP' GROUP BY plugin_slug"
        ):
            mined[slug] = n
        con.close()
    except sqlite3.Error:
        pass
    return mined


def load_diff_audited(retention_days=None):
    """Set of "slug@version" pairs already diff-audited (durable section-A ledger).

    Consulted by rank_targets to suppress a version whose completed diff-audit left
    no on-disk marker _is_real_audit can see (an audit that found nothing, or a
    version-string drift). Imported lazily so audit_targets has no hard dependency on
    the ledger module and no import cycle (diff_audited_ledger must not import this)."""
    try:
        import diff_audited_ledger
    except Exception:
        return set()
    try:
        if retention_days is None:
            return diff_audited_ledger.audited_pairs()
        return diff_audited_ledger.audited_pairs(retention_days)
    except Exception:
        return set()


def parse_dt(s):
    if not s:
        return None
    for fmt in ("%Y-%m-%d %H:%M:%S", "%Y-%m-%d"):
        try:
            return datetime.strptime(s[:19], fmt)
        except ValueError:
            continue
    return None


def online_current_version(slug, timeout=15):
    import urllib.request
    try:
        with urllib.request.urlopen(WP_API.format(slug=slug), timeout=timeout) as r:
            data = json.loads(r.read().decode("utf-8", "replace"))
        return data.get("version")
    except Exception:
        return None


def install_weight(installs):
    # rough bounty-multiplier proxy
    if installs >= 1_000_000: return 5.0
    if installs >= 500_000:   return 4.0
    if installs >= 100_000:   return 3.0
    if installs >= 50_000:    return 2.0
    if installs >= 10_000:    return 1.0
    return 0.5


def rank_targets(plugins, mined, online=False, online_budget=60, min_installs=0,
                 max_installs=0, skip_mined=False, sleep=0.4, diff_audited=None):
    """Split tracked plugins into the two edge queues, ranked by EV proxy.

    Returns (new_release, never, polled). Each queue is a list of record dicts.
    `min_installs` / `max_installs` bound the install band (max_installs <= 0 means
    no ceiling) — a ceiling lets you skip the heavily-contested mega-plugins and focus
    on smaller, less-picked-over targets. When `online`, polls the WP API (highest-
    install audited plugins first, so a limited budget is spent where it matters) to
    catch releases shipped since the tier DBs were last refreshed.
    `diff_audited` is a set of "slug@version" pairs (the durable section-A ledger); a
    candidate whose resolved current version is in it is suppressed from BOTH queues,
    so a completed diff-audit that left no on-disk marker never re-surfaces.
    """
    diff_audited = diff_audited or set()
    now = datetime.now()
    items = [(slug, info) for slug, info in plugins.items()
             if info["installs"] >= min_installs
             and (max_installs <= 0 or info["installs"] <= max_installs)]
    # Spend the online budget on the most valuable plugins first.
    if online:
        items.sort(key=lambda kv: kv[1]["installs"], reverse=True)

    new_release, never = [], []
    polled = 0
    for slug, info in items:
        m = mined.get(slug, 0)
        if skip_mined and m >= MINED_THRESHOLD:
            continue
        av = audited_versions(slug)
        db_v = info["version"]
        latest_audited = max(av, key=vkey) if av else None

        current_v = db_v
        if online and polled < online_budget and av:
            polled += 1
            cur = online_current_version(slug)
            if cur:
                current_v = cur
            if sleep:
                time.sleep(sleep)  # rate-limit guard for wordpress.org

        lu = parse_dt(info["last_updated"])
        days = (now - lu).days if lu else None
        w = install_weight(info["installs"])
        # freshness factor: a release in the last 60d is hot; >2y is cold
        fresh = 2.0 if (days is not None and days <= 60) else (1.0 if (days is not None and days <= 365) else 0.4)

        rec = {
            "slug": slug, "installs": info["installs"], "audited": latest_audited,
            "current": current_v, "last_updated": (info["last_updated"] or "")[:10],
            "days": days, "mined": m,
        }
        # Durable ledger: this exact version was already diff-audited (even if the
        # audit left no marker _is_real_audit could see) -> never re-surface it.
        if f"{slug}@{current_v}" in diff_audited:
            continue
        if not av:
            rec["score"] = w * 1.5  # never audited: first-pass value, modest freshness boost
            never.append(rec)
        elif vkey(current_v) > vkey(latest_audited):
            # NEW RELEASE you have not diff-audited -> the Edge 1 sweet spot
            rec["score"] = w * fresh * 2.0
            new_release.append(rec)

    new_release.sort(key=lambda r: r["score"], reverse=True)
    never.sort(key=lambda r: r["score"], reverse=True)
    return new_release, never, polled


def _mined_note(rec):
    n = rec.get("mined", 0)
    return f"   [mined:{n} - picked over]" if n else ""


def _diff_md_path(slug, version):
    return os.path.join(AUDIT_DIR, slug, version, "DIFF.md")


def has_diff_md(slug, version):
    """True if a pre-generated DIFF.md exists at audit/<slug>/<version>/."""
    return bool(version) and os.path.exists(_diff_md_path(slug, version))


def _diff_prepared_version(slug, current_v):
    """The version that already has a DIFF.md ready (the resolved current version,
    else the newest copy on disk — tolerates online/offline version drift), or None."""
    for v in (current_v, newest_local_version(slug)):
        if v and os.path.exists(_diff_md_path(slug, v)):
            return v
    return None


def prep_state_diff(slug, current_v):
    """(state, version) for an Edge-1 diff item, from on-disk artifacts.
    state: 'ready' (DIFF.md + Semgrep scan), 'partial' (DIFF.md only), 'none'."""
    pv = _diff_prepared_version(slug, current_v)
    if not pv:
        return "none", None
    return ("ready" if has_semgrep_scan(slug, pv) else "partial"), pv


def prep_state_never(slug, current_v=None):
    """(state, version) for an Edge-3 never-audited item: 'ready' (source + scan),
    'partial' (source downloaded, no scan), 'none'. If `current_v` is known and the
    only copy on disk is OLDER, report 'none' — the pipeline audits the highest local
    version, so a stale copy must be refreshed (prep), not skipped."""
    pv = newest_local_version(slug)
    if not pv:
        return "none", None
    if current_v and vkey(pv) < vkey(current_v):
        return "none", pv  # on-disk copy is stale; prep should re-download the current one
    return ("ready" if has_semgrep_scan(slug, pv) else "partial"), pv


_READY_TAG = {"ready": "   ✓ prepared", "partial": "   ◑ partly prepared"}


def _ready_tag(state):
    return _READY_TAG.get(state, "")


def render_targets_md(new_release, never, top=40, variant_md=None,
                      generator="audit_targets.py", date=None):
    """Render the copy-paste checklist. `variant_md` (Edge 2) is inserted as
    section B between the diff queue (A) and the never-audited queue (C)."""
    date = date or datetime.now().strftime("%Y-%m-%d")
    L = [f"# Audit Targets - {date}   (generated by {generator})", ""]
    L.append("Sections are in expected-value order. Each item has the exact prep "
             "command and the exact Full Audit Pipeline trigger to paste into a "
             "fresh Claude session.")
    L.append("")

    L.append("## A. DIFF-AUDIT - new release since your last audit (Edge 1, highest EV)")
    if new_release:
        for r in new_release[:top]:
            state, _ = prep_state_diff(r['slug'], r['current'])
            L.append(f"- [ ] {r['slug']}  ({r['installs']:,} installs)  "
                     f"{r['audited']} → {r['current']}{_mined_note(r)}{_ready_tag(state)}")
            if state == "ready":
                L.append("      prep:  ✓ DIFF.md + Semgrep scan ready — skip prep; go to audit:")
            elif state == "partial":
                L.append(f"      prep:  ◑ DIFF.md ready, no Semgrep scan — "
                         f"python diff_audit.py {r['slug']} --scan")
            else:
                L.append(f"      prep:  python diff_audit.py {r['slug']} --scan   "
                         f"(writes DIFF.md + Semgrep pre-scan; drop --scan for DIFF.md only)")
            L.append(f"      audit: Audit {r['slug']} with Full Audit Pipeline   "
                     f"(prioritize files listed in DIFF.md)")
    else:
        L.append("_(none - every tracked plugin's current release is already audited)_")
    L.append("")

    if variant_md is not None:
        L.append(variant_md.rstrip())
        L.append("")

    L.append("## C. NEVER AUDITED - first pass (Edge 3 shortlist)")
    if never:
        for r in never[:top]:
            state, _ = prep_state_never(r['slug'], r.get('current'))
            L.append(f"- [ ] {r['slug']}  ({r['installs']:,} installs)"
                     f"{_mined_note(r)}{_ready_tag(state)}")
            if state == "ready":
                L.append("      prep:  ✓ source + Semgrep scan ready — skip prep; go to audit:")
            elif state == "partial":
                L.append(f"      prep:  ◑ source downloaded, no Semgrep scan — "
                         f"python wp-plugin-downlauditor.py --plugin {r['slug']} -m audit --config ./semgrep_rules")
            else:
                L.append(f"      prep:  python wp-plugin-downlauditor.py --plugin {r['slug']} "
                         f"-m both --config ./semgrep_rules   (download + Semgrep pre-scan)")
            L.append(f"      audit: Audit {r['slug']} with Full Audit Pipeline")
    else:
        L.append("_(none)_")
    L.append("")
    return "\n".join(L)


def newest_local_version(slug):
    """Highest version dir currently on disk under plugins/<slug>/, or None."""
    d = os.path.join(PLUGINS_DIR, slug)
    if not os.path.isdir(d):
        return None
    vers = [v for v in os.listdir(d) if os.path.isdir(os.path.join(d, v))]
    return max(vers, key=vkey) if vers else None


def _run_with_progress(cmd, label, cwd=None, timeout=900, progress=False):
    """Run a subprocess. When `progress` AND stdout is a TTY, animate a single-line
    elapsed-time spinner while it runs (child output is captured to a temp file so it
    can't clobber the line, and the pipe-buffer deadlock is avoided); otherwise behave
    exactly like subprocess.run(capture_output=True). Returns a CompletedProcess with
    combined child output in .stdout. Raises subprocess.TimeoutExpired past `timeout`."""
    is_tty = getattr(sys.stdout, "isatty", lambda: False)()
    if not (progress and is_tty):
        return subprocess.run(cmd, cwd=cwd, capture_output=True, text=True, timeout=timeout)
    import tempfile
    start = time.time()
    spin = "|/-\\"
    with tempfile.TemporaryFile() as tf:
        proc = subprocess.Popen(cmd, cwd=cwd, stdout=tf, stderr=subprocess.STDOUT)
        i = 0
        while proc.poll() is None:
            el = time.time() - start
            if el > timeout:
                proc.kill()
                proc.wait()
                raise subprocess.TimeoutExpired(cmd, timeout)
            sys.stdout.write(f"\r        {label} {spin[i % 4]} {el:4.0f}s ")
            sys.stdout.flush()
            i += 1
            time.sleep(0.2)
        sys.stdout.write("\r" + " " * (len(label) + 28) + "\r")
        sys.stdout.flush()
        tf.seek(0)
        output = tf.read().decode("utf-8", "replace")
    return subprocess.CompletedProcess(cmd, proc.returncode, output, "")


def prepare_targets(records, n, verbose=True, scan=False, progress=False):
    """Download the top `n` items (latest version) via the downloader subprocess so
    the Full Audit Pipeline / diff_audit can run immediately. Idempotent: the
    downloader skips versions already on disk. When `scan`, also run the project's
    Semgrep rules over each downloaded version so the pipeline finds a pre-scan.
    `progress` shows a live spinner during each download/scan (TTY only).
    Returns list of (slug, version|None)."""
    done = []
    seen = set()
    for rec in records:
        if len(done) >= n:
            break
        slug = rec["slug"]
        if slug in seen:
            continue
        seen.add(slug)
        before = newest_local_version(slug)
        cmd = [sys.executable, DOWNLOADER, "--plugin", slug, "-d", ROOT]
        try:
            proc = _run_with_progress(cmd, f"downloading {slug}", timeout=300, progress=progress)
        except subprocess.TimeoutExpired:
            if verbose:
                print(f"  [prepare] {slug}: TIMEOUT")
            done.append((slug, None))
            continue
        after = newest_local_version(slug)
        if after and after != before:
            status = f"downloaded {after}"
        elif after:
            status = f"already present ({after})"
        else:
            tail = (proc.stderr or proc.stdout or "").strip().splitlines()
            status = "FAILED: " + (tail[-1] if tail else f"rc={proc.returncode}")
        if verbose:
            print(f"  [prepare] {slug}: {status}")
        if scan and after:
            ensure_semgrep_scan(slug, after, verbose=verbose, progress=progress)
        done.append((slug, after))
    return done


def has_semgrep_scan(slug, version):
    """True if plugins/<slug>/<version>/semgrep-scan/ already holds scan output."""
    d = os.path.join(PLUGINS_DIR, slug, version, "semgrep-scan")
    try:
        return any(f.endswith(".json") for f in os.listdir(d))
    except OSError:
        return False


def ensure_semgrep_scan(slug, version, verbose=True, timeout=900, progress=False):
    """Run the project's custom Semgrep rules over plugins/<slug>/<version>/ so the
    Full Audit Pipeline finds a pre-scan (extract_semgrep_coords.py reads the
    semgrep-scan/ dir). Without this, a freshly-downloaded version enters the
    pipeline missing the whole Semgrep lead layer every other plugin has.

    Idempotent (skips if output already exists). Reuses the downloader's audit mode,
    which scans an already-on-disk version in place with the SAME custom-rule corpus
    the rest of the DB used (so pattern_accumulator stats stay coherent). Non-fatal:
    returns True on success, False otherwise — a scan failure never aborts prep."""
    if has_semgrep_scan(slug, version):
        if verbose:
            print(f"  [scan ] {slug} {version}: already scanned")
        return True
    if not os.path.isdir(os.path.join(PLUGINS_DIR, slug, version)):
        if verbose:
            print(f"  [scan ] {slug} {version}: source not on disk — skipped")
        return False
    # Run from ROOT with a RELATIVE -d so Semgrep records plugin-relative paths
    # ("plugins/<slug>/<v>/...") exactly like the rest of the corpus — extract_semgrep_coords.py
    # and the summary's path-prefix stripping both depend on that format.
    cmd = [sys.executable, DOWNLOADER, "--plugin", slug, "--version", version,
           "-m", "audit", "-d", "."]
    if os.path.isdir(RULES_DIR):
        cmd += ["--config", RULES_DIR]  # match the corpus (custom rules), not p/php
    try:
        _run_with_progress(cmd, f"scanning {slug} {version}", cwd=ROOT,
                           timeout=timeout, progress=progress)
    except subprocess.TimeoutExpired:
        if verbose:
            print(f"  [scan ] {slug} {version}: TIMEOUT after {timeout}s")
        return False
    ok = has_semgrep_scan(slug, version)
    if ok:
        _normalize_scan_json(slug, version)
    if verbose:
        print(f"  [scan ] {slug} {version}: "
              + ("scanned" if ok else "FAILED (is semgrep installed / on PATH?)"))
    return ok


def _normalize_scan_json(slug, version):
    """Rewrite Semgrep JSON 'path' separators to '/' so a Windows scan matches the
    forward-slash format the rest of the corpus (and extract_semgrep_coords.py) uses."""
    d = os.path.join(PLUGINS_DIR, slug, version, "semgrep-scan")
    try:
        for fn in os.listdir(d):
            if not fn.endswith(".json"):
                continue
            fp = os.path.join(d, fn)
            with open(fp, encoding="utf-8") as f:
                data = json.load(f)
            changed = False
            for r in data.get("results", []):
                p = r.get("path")
                if p and "\\" in p:
                    r["path"] = p.replace("\\", "/")
                    changed = True
            if changed:
                with open(fp, "w", encoding="utf-8") as f:
                    json.dump(data, f, separators=(",", ":"))
    except (OSError, ValueError):
        pass


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--top", type=int, default=40)
    ap.add_argument("--min-installs", type=int, default=0)
    ap.add_argument("--max-installs", type=int, default=0,
                    help="Rank only plugins with AT MOST this many installs (0 = no cap). "
                         "Focus on less-contested smaller plugins, e.g. --max-installs 500000")
    ap.add_argument("--online", action="store_true",
                    help="Poll wordpress.org for TRUE current version (catches releases since DB refresh)")
    ap.add_argument("--online-budget", type=int, default=60, help="Max online polls (rate-limit guard)")
    ap.add_argument("--skip-mined", action="store_true",
                    help=f"Drop plugins with >={MINED_THRESHOLD} confirmed findings (picked over)")
    ap.add_argument("--out", default="targets.md",
                    help="Write the copy-paste checklist here (default: targets.md)")
    ap.add_argument("--prepare", type=int, default=0, metavar="N",
                    help="Download the top N ranked items so they are immediately audit-ready")
    args = ap.parse_args()

    plugins = load_db_plugins()
    mined = load_mined_slugs()
    diff_audited = load_diff_audited()

    new_release, never, polled = rank_targets(
        plugins, mined, online=args.online, online_budget=args.online_budget,
        min_installs=args.min_installs, max_installs=args.max_installs,
        skip_mined=args.skip_mined, diff_audited=diff_audited,
    )

    def show(title, rows, n):
        print(f"\n{'='*78}\n{title}  ({len(rows)} total)\n{'='*78}")
        print(f"{'slug':<42}{'installs':>10}  {'audited':>12} -> {'current':<12} {'updated':<11} mined")
        for r in rows[:n]:
            print(f"{r['slug']:<42}{r['installs']:>10,}  {str(r['audited']):>12} -> "
                  f"{str(r['current']):<12} {r['last_updated']:<11} {r['mined'] or ''}")

    n_audited = sum(1 for p in plugins if audited_versions(p))
    print(f"[audit_targets] {len(plugins)} plugins in DBs | {n_audited} audited | "
          f"online polls: {polled}"
          + (f" | skip-mined>={MINED_THRESHOLD}" if args.skip_mined else ""))
    show("A) NEW RELEASE since your audit -> DIFF-AUDIT (Edge 1, highest EV)", new_release, args.top)
    show("B) NEVER AUDITED -> first-pass (Edge 3 shortlist)", never, args.top)
    if not args.online:
        print("\n[note] offline mode compares against DB-recorded versions (DBs last refreshed "
              "Apr-May). Run with --online to catch releases shipped since then.")

    # Write the copy-paste checklist.
    md = render_targets_md(new_release, never, top=args.top)
    out_path = args.out if os.path.isabs(args.out) else os.path.join(ROOT, args.out)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(md)
    print(f"\n[audit_targets] wrote checklist -> {out_path}")

    if args.prepare:
        print(f"\n[audit_targets] preparing top {args.prepare} item(s) for audit...")
        combined = new_release + never  # diff items first (higher EV)
        prepare_targets(combined, args.prepare)


if __name__ == "__main__":
    main()
