<?php
// ruleid: claude.php.wordpress.file.arbitrary-file-read
echo file_get_contents($_GET['path']);

$name = $_POST['file'];
// ruleid: claude.php.wordpress.file.arbitrary-file-read
readfile(WP_CONTENT_DIR . '/uploads/' . $name);

$f = $_REQUEST['f'];
// ruleid: claude.php.wordpress.file.arbitrary-file-read
$lines = file("/var/log/" . $f);

// ok: claude.php.wordpress.file.arbitrary-file-read
$name = basename($_POST['file']);
readfile(WP_CONTENT_DIR . '/uploads/' . $name);

// ok: claude.php.wordpress.file.arbitrary-file-read
file_get_contents(WP_CONTENT_DIR . '/fixed.txt');

// ok: claude.php.wordpress.file.arbitrary-file-read
$url = esc_url_raw($_GET['url']);
file_get_contents($url);

// ── $_FILES tests ─────────────────────────────────────────────────────────────

// VULNERABLE: attacker controls the original filename; plugin uses it as a path.
$original_name = $_FILES['upload']['name'];
// ruleid: claude.php.wordpress.file.arbitrary-file-read
$data = file_get_contents(WP_CONTENT_DIR . '/uploads/' . $original_name);

// VULNERABLE: full_path is also attacker-supplied (PHP 8.1 relative paths feature).
$path = $_FILES['upload']['full_path'];
// ruleid: claude.php.wordpress.file.arbitrary-file-read
readfile($path);

// SAFE: tmp_name is generated by PHP (e.g. /tmp/phpXXXXXX) — not attacker-controlled.
// This was a false positive in earlier versions of the rule.
$tmp = $_FILES['upload']['tmp_name'];
// ok: claude.php.wordpress.file.arbitrary-file-read
$json = file_get_contents($tmp);

// SAFE: basename() strips directory traversal from the attacker-controlled name.
$safe = basename($_FILES['upload']['name']);
// ok: claude.php.wordpress.file.arbitrary-file-read
readfile(WP_CONTENT_DIR . '/uploads/' . $safe);

// ── preg_replace whitelist sanitizer tests ────────────────────────────────────

// VULNERABLE: preg_replace with a blacklist (only strips slashes, not dots).
// An attacker can still use ../ via encoded or alternative traversal sequences.
$name = $_POST['layout'];
$name = preg_replace('/\//', '', $name);  // only strips /, not .
// ruleid: claude.php.wordpress.file.arbitrary-file-read
$content = file_get_contents(get_stylesheet_directory() . '/templates/' . $name . '.txt');

// SAFE: strict allowlist preg_replace — permits only [a-zA-Z0-9_\-\+],
// stripping . and / entirely; path traversal is impossible without these chars.
// Exact pattern from bold-page-builder 5.7.2 bold-builder-fe.php:810.
$layout = sanitize_text_field($_POST['layout']);
$layout = preg_replace('/[^a-zA-Z0-9_\-\+]/', '', $layout);
// ok: claude.php.wordpress.file.arbitrary-file-read
$content = @file_get_contents(get_stylesheet_directory() . '/bold-page-builder/templates/' . str_replace('+', '_', $layout) . '.txt');

// SAFE: double-quoted variant of the same allowlist pattern.
$layout2 = sanitize_text_field($_POST['layout']);
$layout2 = preg_replace("/[^a-zA-Z0-9_\\-\\+]/", '', $layout2);
// ok: claude.php.wordpress.file.arbitrary-file-read
$content2 = @file_get_contents(get_stylesheet_directory() . '/templates/' . $layout2 . '.txt');

// ── sanitize_key() sanitizer tests ───────────────────────────────────────────

// VULNERABLE: raw $_GET used in readfile() path — no sanitizer.
$log = $_GET['log'];
// ruleid: claude.php.wordpress.file.arbitrary-file-read
readfile(WP_CONTENT_DIR . '/logs/' . $log . '.log');

// SAFE: sanitize_key() restricts output to [a-z0-9_-] — no / or . possible,
// so directory traversal is impossible. Confirmed pattern: litespeed-cache
// debug2.cls.php readfile() path built from sanitize_key($_GET['log']).
$log_key = sanitize_key(wp_unslash($_GET['log']));
// ok: claude.php.wordpress.file.arbitrary-file-read
readfile(WP_PLUGIN_DIR . '/myplugin/logs/' . $log_key . '.log');

// ── in_array() strict allowlist-membership gate (by-side-effect) ────────────

// SAFE: the tainted value is checked with strict in_array(..., true)
// membership against an existing-values array (here, a scandir()-derived
// log filename list) before the sink runs — the attacker can only select an
// already-existing filename, no traversal possible.
function showEsLogFile() {
    $log_files     = scandir( IG_LOG_DIR );
    $log_file_name = sanitize_text_field( $_POST['log_file'] );
    if ( in_array( $log_file_name, $log_files, true ) ) {
        // ok: claude.php.wordpress.file.arbitrary-file-read
        echo file_get_contents( IG_LOG_DIR . $log_file_name );
    }
}

// KNOWN LIMITATION: this sanitizer trusts in_array($X, $ALLOWLIST, true) as
// a gate regardless of $ALLOWLIST's own provenance — it does not verify
// $ALLOWLIST is itself non-attacker-controlled. In the confirmed real-world
// pattern this was modeled on, $ALLOWLIST is always a filesystem/developer-
// enumerated array (e.g. scandir()); an "allowlist" built from request data
// would be a separate, contrived bug this sanitizer cannot distinguish.

// ── Transient/option/meta used only as an opaque lookup KEY ─────────────────

// SAFE: $_POST['progressID'] is used only as the KEY argument of
// get_transient() — the returned value is the server-computed upload path
// stored earlier by a separate set_transient() call, never a reflection of
// the key's own content.
$progress_id = $_POST['progressID'];
$file_name = get_transient( $progress_id );
// ok: claude.php.wordpress.file.arbitrary-file-read
$fh = fopen( $file_name, 'r' );

// SAFE: same shape via get_option(), request value used only as the option
// name, not as path content.
$opt_name = $_GET['settings_key'];
$stored_path = get_option( $opt_name );
// ok: claude.php.wordpress.file.arbitrary-file-read
readfile( $stored_path );

// VULNERABLE negative control: the get_transient() lookup result is safe,
// but the same $path variable is later reassigned directly from raw request
// data before the sink — flow-sensitive tracking must still re-taint it,
// proving the new sanitizer isn't a function-wide exclusion.
$progress_id2 = $_POST['progressID'];
$path = get_transient( $progress_id2 );
if ( isset( $_GET['debug_path'] ) ) {
    $path = $_GET['debug_path'];
}
// ruleid: claude.php.wordpress.file.arbitrary-file-read
readfile( $path );

// ── WP Core media accessor / named-resolver sanitizer tests ─────────────────

class Media_Server_Safe {
    // SAFE: the attacker-controlled context ID only selects WHICH avatar/
    // attachment is resolved (via WP's own accessors) — never an arbitrary
    // filesystem path.
    public function get_avatar( $request ) {
        $author = $request->get_param( 'author' );
        // ok: claude.php.wordpress.file.arbitrary-file-read
        $path = get_avatar_url( $author );
        readfile( $path );
    }

    public function get_original_image( $request ) {
        $context = $request->get_param( 'context' );
        $image   = get_post_thumbnail_id( $context );
        // ok: claude.php.wordpress.file.arbitrary-file-read
        $path = wp_get_original_image_path( $image );
        readfile( $path );
    }

    // SAFE: sentinel-substitution idiom — a sibling resolver whose name
    // signals path-safety validation is called with the tainted value, and
    // only its OWN validated return is trusted (never the raw input).
    public static function get_safe_fallback_path( $fallback ) {
        $full_path = realpath( sanitize_text_field( $fallback ) );
        if ( false === $full_path ) {
            return '';
        }
        return $full_path;
    }

    public function get( $request ) {
        $fallback      = $request->get_param( 'fallback' );
        $path          = OTTER_BLOCKS_PATH . '/assets/images/placeholder.jpg';
        $safe_fallback = self::get_safe_fallback_path( $fallback );

        if ( '' !== $safe_fallback ) {
            $path = $safe_fallback;
        }

        // ok: claude.php.wordpress.file.arbitrary-file-read
        readfile( $path );
    }

    // VULNERABLE: the same sentinel-substitution idiom appears, but a
    // separate, later branch reassigns $path directly from raw request data
    // — flow-sensitive tracking must still catch this re-taint.
    public function get_mixed_safety( $request ) {
        $fallback      = $request->get_param( 'fallback' );
        $path          = 'default.jpg';
        $safe_fallback = self::get_safe_fallback_path( $fallback );

        if ( '' !== $safe_fallback ) {
            $path = $safe_fallback;
        }

        if ( isset( $_GET['debug_path'] ) ) {
            $path = $_GET['debug_path'];
        }

        // ruleid: claude.php.wordpress.file.arbitrary-file-read
        readfile( $path );
    }
}

// ── GD image-decode function sinks (image-proxy path traversal) ─────────────

// VULNERABLE: image-proxy script builds the path from DOCUMENT_ROOT concatenated
// with an attacker-controlled URL path, with only a file-extension dispatch
// (no traversal-sequence/realpath/prefix-containment check) before decoding.
// Real-world shape: wonderm00ns-simple-facebook-open-graph-tags fbimg.php.
$url = parse_url( urldecode( trim( $_GET['img'] ) ) );
$imgpath = $_SERVER['DOCUMENT_ROOT'] . $url['path'];
// ruleid: claude.php.wordpress.file.arbitrary-file-read
$image = imagecreatefromjpeg( $imgpath );

// VULNERABLE: same shape via imagecreatefrompng(), and getimagesize() used as
// a companion existence/dimension oracle on the same tainted path.
$thumb = $_GET['thumb'];
$thumbpath = WP_CONTENT_DIR . '/cache/' . $thumb;
// ruleid: claude.php.wordpress.file.arbitrary-file-read
$size = getimagesize( $thumbpath );
// ruleid: claude.php.wordpress.file.arbitrary-file-read
$png = imagecreatefrompng( $thumbpath );

// SAFE: basename() strips directory traversal before the GD sink.
$safe_thumb = basename( $_GET['thumb'] );
// ok: claude.php.wordpress.file.arbitrary-file-read
$gif = imagecreatefromgif( WP_CONTENT_DIR . '/cache/' . $safe_thumb );

// SAFE: sanitize_file_name() before the GD sink.
$safe_name = sanitize_file_name( $_GET['img'] );
// ok: claude.php.wordpress.file.arbitrary-file-read
$webp = imagecreatefromwebp( WP_CONTENT_DIR . '/uploads/' . $safe_name );

// VULNERABLE: hand-rolled "auto-detect extension, dispatch to the matching
// imagecreatefrom*() call" wrapper helper, called directly on a tainted path.
$doc_root = $_SERVER['DOCUMENT_ROOT'];
$img_url = parse_url( urldecode( trim( $_GET['img'] ) ) );
// ruleid: claude.php.wordpress.file.arbitrary-file-read
$loaded = imagecreatefromfile( $doc_root . $img_url['path'] );

// SAFE: realpath() canonicalizes before the wrapper-helper sink.
$safe_path = realpath( WP_CONTENT_DIR . '/cache/' . basename( $_GET['img'] ) );
// ok: claude.php.wordpress.file.arbitrary-file-read
$loaded2 = imagecreatefromfile( $safe_path );
